documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
image:
- changed-files:
  - any-glob-to-any-file: '**/*.webp'
vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
ci:
- changed-files:
  - any-glob-to-any-file: ['.github/workflows/*.yml', '.github/dependabot.yml']
enhancement:
 - head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
