♻️ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*.yml'
📝documentation:
- changed-files:
  - any-glob-to-any-file: '**/*.md'
🚀enhancement:
- head-branch: ['^feature', 'feature', '^enhancement', 'enhancement']
🪸git:
- changed-files:
  - any-glob-to-any-file: '.gitattributes'
🖼️image:
- changed-files:
  - any-glob-to-any-file: 'images/**'
🧰infrastructure:
- changed-files:
  - any-glob-to-any-file: '.editorconfig'
🆚vscode:
- changed-files:
  - any-glob-to-any-file: '.vscode/*'
